name: html_to_markdown
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
