name: html_to_markdown
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  common_extensions_utils:
    path: ../common_extensions_utils
  freezed_annotation: ^2.4.1
  html: ^0.15.4
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.0
  very_good_analysis: ^5.1.0
